import React, { useState } from 'react';
import { Alert, Modal, StyleSheet, Switch, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { Feather } from '@expo/vector-icons';
import { useQueryClient } from '@tanstack/react-query';
import { getGetDashboardSummaryQueryKey, Product, useCreateProduct, useDeleteProduct, useListProducts, useUpdateProduct } from '@workspace/api-client-react';
import { Field, IconButton, Notice, Page, PrimaryButton, card } from '@/components/AppUI';
import { useColors } from '@/hooks/useColors';
type Form={name:string;price:string;aliases:string;active:boolean};
const blank:Form={name:'',price:'',aliases:'',active:true};
export default function Products(){
 const c=useColors(),qc=useQueryClient(),q=useListProducts(),create=useCreateProduct(),update=useUpdateProduct(),del=useDeleteProduct(); const [open,setOpen]=useState(false),[editing,setEditing]=useState<Product|null>(null),[form,setForm]=useState<Form>(blank);
 const refresh=()=>void q.refetch(); const invalidate=()=>{qc.invalidateQueries({queryKey:q.queryKey});qc.invalidateQueries({queryKey:getGetDashboardSummaryQueryKey()});}; const close=()=>{setOpen(false);setEditing(null);setForm(blank)};
 const edit=(p?:Product)=>{setEditing(p??null);setForm(p?{name:p.name,price:String(p.price),aliases:p.aliases.join(', '),active:p.active}:blank);setOpen(true)};
 const save=()=>{const price=Number(form.price);if(!form.name.trim()||Number.isNaN(price)||price<0){Alert.alert('פרטים חסרים','יש להזין שם ומחיר תקינים.');return}const data={name:form.name.trim(),price,aliases:form.aliases.split(',').map(x=>x.trim()).filter(Boolean),active:form.active}; const done=()=>{void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);invalidate();close()}; if(editing) update.mutate({id:editing.id,data},{onSuccess:done});else create.mutate({data},{onSuccess:done});};
 const remove=(p:Product)=>Alert.alert('מחיקת מחיר','למחוק את ״'+p.name+'״?', [{text:'ביטול',style:'cancel'},{text:'מחיקה',style:'destructive',onPress:()=>del.mutate({id:p.id},{onSuccess:()=>{void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning);invalidate()}})}]);
 return <Page title="מחירים" subtitle="עדכנו את המחירון שהבוט מציג" refreshing={q.isRefetching} onRefresh={refresh} action={<IconButton icon="plus" testID="add-product" onPress={()=>edit()}/>}>
  {q.isError?<Notice icon="wifi-off" title="לא ניתן לטעון מחירים" text="נסו לרענן את הרשימה." retry={refresh}/>:q.isLoading?<Notice icon="loader" title="טוען מחירון" text="רק רגע…"/>:q.data?.length?q.data.map(p=><View key={p.id} style={[styles.row,...card(c)]}><View style={{flex:1}}><Text style={[styles.name,{color:c.foreground}]}>{p.name}</Text><Text style={[styles.meta,{color:c.mutedForeground}]}>{p.aliases.length? p.aliases.join(' · ') : 'ללא שמות חלופיים'}</Text></View><View style={styles.price}><Text style={[styles.amount,{color:c.foreground}]}>{p.price} {p.currency}</Text><View style={styles.actions}><IconButton icon="edit-2" testID={`edit-product-${p.id}`} onPress={()=>edit(p)}/><IconButton icon="trash-2" destructive testID={`delete-product-${p.id}`} onPress={()=>remove(p)}/></View></View></View>):<Notice icon="tag" title="המחירון עדיין ריק" text="הוסיפו את המחיר הראשון כדי שהבוט יוכל לענות."/>}
  <Modal visible={open} animationType="slide" transparent onRequestClose={close}><View style={styles.overlay}><View style={[styles.sheet,{backgroundColor:c.background}]}><Text style={[styles.sheetTitle,{color:c.foreground}]}>{editing?'עריכת מחיר':'מחיר חדש'}</Text><Field label="שם הפריט" value={form.name} onChangeText={v=>setForm({...form,name:v})}/><Field label="מחיר" value={form.price} keyboardType="numeric" onChangeText={v=>setForm({...form,price:v})}/><Field label="שמות חלופיים" value={form.aliases} placeholder="מופרדים בפסיקים" onChangeText={v=>setForm({...form,aliases:v})}/><View style={styles.toggle}><Text style={[styles.meta,{color:c.foreground}]}>מוצג בבוט</Text><Switch testID="product-active-switch" value={form.active} onValueChange={v=>setForm({...form,active:v})} trackColor={{true:c.primary}}/></View><PrimaryButton label="שמירת מחיר" testID="save-product" onPress={save} loading={create.isPending||update.isPending}/><PrimaryButton label="ביטול" testID="cancel-product" onPress={close}/></View></View></Modal>
 </Page>
}
const styles=StyleSheet.create({row:{flexDirection:'row-reverse',alignItems:'center',gap:10},name:{fontFamily:'Inter_700Bold',fontSize:16,textAlign:'right'},meta:{fontFamily:'Inter_400Regular',fontSize:12,textAlign:'right',marginTop:5},price:{alignItems:'flex-end'},amount:{fontFamily:'Inter_700Bold',fontSize:15},actions:{flexDirection:'row-reverse',marginTop:3},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.35)'},sheet:{borderTopLeftRadius:20,borderTopRightRadius:20,padding:20,gap:13},sheetTitle:{fontFamily:'Inter_700Bold',fontSize:21,textAlign:'right',marginBottom:3},toggle:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'}});